name: bgmi_uc_shop  # Aapke project ka jo bhi naam ho
description: A new Flutter project.

# Ye wala section add karna zaroori hai 👇
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
