name: bgmi
description: Rooter Shop - BGMI UC & Gaming Store
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  firebase_database: ^10.5.7

  # UPI payments
  upi_india: ^3.0.1

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Date formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true